### ISSUE TITLE
Matrix size mismatch between host and kernel for the 1-The_Smith-Waterman_example_in_details/1-On_how_to_optimize_the_Smith-Waterman_solution/1-A_first_implementation/initial_code

### ISSUE THREAD

**Issue by linusyukwong** [necst/coursera-sdaccel-practice#1]
The #define N 128 on line 14 of maincl.cpp should be #define N 256

**Comment by lorenzoditucci** [comment]
Hi @linusyukwong, thanks for pointing this out! The inital_code folder contains the starting point code for the lesson, but the host file is not modified in the specific video.
I will fix it right now.
